src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
Allow configuring the dataset mean and std. Used to be hard coded.
Also fixed some lint issues on the way
=> add configurable img_mean, img_std + lint issues

src/super_gradients/recipes/cityscapes_stdc_seg50.yaml, src/super_gradients/recipes/coco2017_yolov5.yaml, src/super_gradients/recipes/imagenet_efficientnet.yaml, src/super_gradients/recipes/imagenet_mobilenetv2.yaml, src/super_gradients/recipes/imagenet_mobilenetv3.yaml, src/super_gradients/recipes/imagenet_regnetY.yaml, src/super_gradients/recipes/imagenet_repvgg.yaml, src/super_gradients/recipes/imagenet_resnet50.yaml
Multi gpu arg is not passed to sg_mode in yaml files- fixed.
=> yaml files fixed

src/super_gradients/training/losses/yolox_loss.py
As requested, adding more comments explaining every step of the loss
=> docs: Comment all the stages of the loss

src/super_gradients/training/utils/ssd_utils.py
Steps is the hardcoded variable that defines output stride of each predicting level. But we already have input size and feat side `DefaultBoxes`, so steps are calculable and it's error-prone to hard-code them. 
It's not used anywhere outside, only in
`fk = fig_size / np.array(steps)` 
where it calculates exactly feat_size, but with some rounding errors. 
Bottom line: it's more correct to just use the `feat_size` list directly instead of `fig_size / steps`
=> fix: Get rid of steps

src/super_gradients/training/models/classification_models/mobilenetv2.py
=> fix: Update connectors name in mobilenetv2

src/super_gradients/training/kd_model/kd_model.py, src/super_gradients/training/sg_model/sg_model.py, tests/unit_tests/kd_model_test.py
Checkpoint saving for best checkpoints logic changed in KDModel to support weight loading in SgModel for the student.
=> Save student only in ckpt_best for KD

src/super_gradients/training/kd_model/kd_model.py, src/super_gradients/training/sg_model/sg_model.py, src/super_gradients/training/utils/quantization_utils.py, tests/end_to_end_tests/trainer_test.py, tests/unit_tests/strictload_enum_test.py
fix naming of private functions
remove unusable functions
=> fix naming of private functions

src/super_gradients/training/models/detection_models/yolov5_base.py, src/super_gradients/training/utils/detection_utils.py
… and agnostic parameters; Added some documentations; Added flag for yolo score treatment (objectness multiply by class scores); apllied max number of predictions out of nms function
=> feature/SG-175 New NMS

src/super_gradients/training/utils/detection_utils.py
Fix a bug where the computation of recall/precision would crash when all the confidence scores are above the "score_threshold".
=> Fix compute of precision & recall

src/super_gradients/recipes/anchors/ssd_anchors.yaml, src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml, src/super_gradients/recipes/coco2017_ssd_mobilenet_v1.yaml, src/super_gradients/training/models/detection_models/ssd.py, src/super_gradients/training/pretrained_models.py, src/super_gradients/training/utils/ssd_utils.py, tests/integration_tests/pretrained_models_test.py
Adding:
* yaml
* weights
* weights map test
Also a small fix in the NMS callback, it crashes now
=> SSD Mobile V1

src/super_gradients/common/factories/transforms_factory.py, src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py, src/super_gradients/training/datasets/segmentation_datasets/segmentation_dataset.py
Refactored SegmentationDataset and made CityscapesDatasetInterface backwards compatible
=>  feature/sg-223-segmentation-dataset-refactor

src/super_gradients/training/datasets/segmentation_datasets/cityscape_segmentation.py, src/super_gradients/training/datasets/segmentation_datasets/coco_segmentation.py, src/super_gradients/training/datasets/segmentation_datasets/supervisely_persons_segmentation.py
https://github.com/Deci-AI/super-gradients/issues/351
=> Segmentation dataset cache fix

src/super_gradients/training/dataloaders/dataloaders.py
Helpful to see the defaults after construction with them
=> feature: Allow to see default params

src/super_gradients/training/utils/distributed_training_utils.py
When gpu_mode is AUTO- gpu_mode is set to DDP if multiple devices are available.
=> ddp logic changed

src/super_gradients/training/sg_trainer/sg_trainer.py, src/super_gradients/training/utils/sg_trainer_utils.py
=> Feature-177/Add message with effective batch size when training

requirements.txt
=> wheel>=0.38.0 

src/super_gradients/training/dataloaders/dataloaders.py
Respect the drop_last parameter when batch_sampler is enabled
=> Fix drop_last support in BatchSampler

src/super_gradients/training/utils/module_utils.py
Sub-PR for #481, a fix for `MultiOutputModule`
=> fix: Support hydra lists

tests/integration_tests/pretrained_models_test.py
Sub-PR for #481, just formatting
=> refactor: Format pretrained_models_test

src/super_gradients/training/sg_trainer/sg_trainer.py
=> Use Gloo backend when running on Windows

README.md
- Collapse in advanced features
- Adding model zoo links
=> Reorganisation README

src/super_gradients/training/models/segmentation_models/common.py, src/super_gradients/training/models/segmentation_models/ppliteseg.py, src/super_gradients/training/models/segmentation_models/stdc.py, src/super_gradients/training/models/segmentation_models/unet/unet.py
Implemented the replace head for UNetCustom module.
Extracted duplicated code of SegmentationHead module to common.py file
=> replace head for UNet module

src/super_gradients/__init__.py, src/super_gradients/common/__init__.py, src/super_gradients/common/crash_handler/crash_tips.py, src/super_gradients/training/utils/hydra_utils.py, tests/deci_core_unit_test_suite_runner.py, tests/unit_tests/__init__.py, tests/unit_tests/crash_tips_test.py
- Add version_base to hydra to remove warning
- Add Crashtip to help user in case he is using wrong version and gets an error
- Add Crashtip to CI test
=> Add version_base to hydra to remove warning

src/super_gradients/training/utils/detection_utils.py
There are bunch of black-related changes, but changes in question are these two lines:
https://github.com/Deci-AI/super-gradients/pull/566/files#diff-704b8d5cb142a02bea1be07634201556203fe6f2a0d17e5ad6216b73c0f07fbbR1062
https://github.com/Deci-AI/super-gradients/pull/566/files#diff-704b8d5cb142a02bea1be07634201556203fe6f2a0d17e5ad6216b73c0f07fbbR1097
=> Fix runtime warning of accessing non-contiguous tensor in mAP metric

README.md, requirements.txt, src/super_gradients/__init__.py
- Version support for RC.
- Requirements.txt fix for pistols
- Readme.md links fix for docker hub.
=> version and readme fix

src/super_gradients/training/sg_trainer/sg_trainer.py, src/super_gradients/training/utils/checkpoint_utils.py
All the fields that were stored for other checkpoints (best, latest) are now added to average.
=> Add metadata to average_model

src/super_gradients/training/utils/quantization/export.py
=> Removed enable_onnx_checker from export to be compatible with torch 1.11+

src/super_gradients/recipes/dataset_params/coco_detection_dataset_params.yaml, src/super_gradients/recipes/dataset_params/coco_detection_ppyoloe_dataset_params.yaml, src/super_gradients/recipes/dataset_params/coco_detection_ssd_lite_mobilenet_v2_dataset_params.yaml
I don't really see a point to keep crowd=False, knowing that it doesnt increase by a lot the running time of validation, AND we report with crowd.
=> add crowd to recipes

src/super_gradients/training/transforms/transforms.py
Fix incorrect behavior of affine transform when applied to images of resolution bigger than the target one
=> fix: Center detection affine

src/super_gradients/training/losses/yolox_loss.py, tests/unit_tests/yolox_unit_test.py
When no targets were present in batch, the loss failed to handle it correctly
=> Fix YoloX loss to handle negative batch correctly

mkdocs.yml
=> add missing files

.circleci/config.yml
This change will allow external users to use the CI when contributing code
=> remove unnecessary login to codeartifact on normal branch

.circleci/config.yml, README.md, documentation/source/experiment_monitoring.md, src/super_gradients/common/sg_loggers/__init__.py, src/super_gradients/common/sg_loggers/dagshub_sg_logger.py
@timho102003 has added code to introduce a DagsHub logger to Super Gradients. Please let us know if there are any questions.
It uses MLflow and DVC under the hood to track experiment parameters and metrics while versioning the datasets and models used, and pushes all the above to your DagsHub repository.
Example DagsHub repository with the logger:
https://dagshub.com/timho102003/super_grad_test_v2
=> Add DagsHub Logger to Super Gradients

src/super_gradients/training/datasets/detection_datasets/detection_dataset.py, src/super_gradients/training/datasets/segmentation_datasets/coco_segmentation.py, src/super_gradients/training/datasets/segmentation_datasets/segmentation_dataset.py, src/super_gradients/training/sg_trainer/sg_trainer.py
https://deci.atlassian.net/browse/SG-843
=> Fix not-closed tqdm

tutorials/what_are_recipes_and_how_to_use.ipynb
@Louis-Dupont as requested.
Looks like it does not strip outputs, innit?
=> Update the notebooks to install super_gradients==3.1

src/super_gradients/training/pipelines/pipelines.py
This will make image prediction a list instead of a generator when running on single image (which was not intended)
=> Force predictions as list

docs/welcome.html
=> Fix typo in welcome.html

src/super_gradients/training/models/conversion.py, tests/unit_tests/export_onnx_test.py
Fixes bug https://github.com/Deci-AI/super-gradients/issues/978
=> Fix convert_to_onnx to correctly handle case when input_shape is None

src/super_gradients/training/models/conversion.py
Update docs for convert_to_coreml
=> replace documentation 'onnx' with 'coreml'

src/super_gradients/training/sg_trainer/sg_trainer.py
Removing `self.dataset_params` and just computing it when needed (this happens only once anyway).
Not solving any bug, but easier to update the code that way, because the instantiation of that variable and the usage will now be one next to the other.
=> Remove `self.dataset_params`

src/super_gradients/training/sg_trainer/sg_trainer.py
Rewriting `_set_preprocessing_from_valid_loader` to be `_get_preprocessing_from_valid_loader`, which that way can be used in 2 places instead of one
=> Rewrite `_set_preprocessing_from_valid_loader` to `_get_preprocessing_from_valid_loader`

src/super_gradients/common/object_names.py, src/super_gradients/training/transforms/transforms.py, tests/unit_tests/transforms_test.py
Adds DetectionVerticalFlip for bounding box detection augmentation.
Resolves: https://github.com/Deci-AI/super-gradients/issues/1161
Discussion:
https://github.com/Deci-AI/super-gradients/pull/1165
=> Add DetectionVerticalFlip

src/super_gradients/training/transforms/transforms.py, tests/unit_tests/preprocessing_unit_test.py
Fixes https://github.com/Deci-AI/super-gradients/issues/1122
=> Fix a bug in implementation of DetectionRGB2BGR.get_equivalent_preprocessing

YOLONAS.md
Fix SyntaxError through delete "."
=> Fix invalid syntax at YOLONAS.md

src/super_gradients/training/sg_trainer/sg_trainer.py
It looks like our soft-termination was not implemented properly and never triggered an actual stop.
Fixed that and handled the DDP case as well.
=> Correctly handle Ctrl-C event

src/super_gradients/training/models/model_factory.py, src/super_gradients/training/utils/checkpoint_utils.py, tests/unit_tests/pretrained_models_unit_test.py
Same as https://github.com/Deci-AI/super-gradients/pull/1473 but to master_320
=> Fixed loading preprocessing params from pretrained weights (#1473)

.circleci/config.yml
(cherry picked from commit 811c0f5a4c9bc0395734d3b8d9182a8e46ad4292)
=> tests skipped (#1509)

src/super_gradients/training/sg_trainer/sg_trainer.py, src/super_gradients/training/utils/checkpoint_utils.py
* fixed cyclic lr state dict
---------
Co-authored-by: Eugene Khvedchenya <ekhvedchenya@gmail.com>
(cherry picked from commit b56fad8ebc5a1842969dcebc237dbd6b426ba6d4)
=> fixed cyclic lr state dict (#1469)

src/super_gradients/common/deprecate.py
cherry picking https://github.com/Deci-AI/super-gradients/pull/1542 to master_330
=> Fix training_params deprecation

CONTRIBUTING.md
Hi all!
This is my first time opening a pull request to this project, I just got acquainted with how to make signed commits.
I suggested that it would be great to go through the file and propose some changes in places that seemed not obvious to me while following the instructions (just to make it look tidier).
Changes:
1. Fixed quotes in Jupyter Notebook section
2. Replaced the explicit key example with a placeholder for it
3. Added "making signed commit" and "gpg debug" sections (encountered ones ;) )
=> Fixing typos and adding extra info to CONTRIBUTING

src/super_gradients/training/sg_trainer/sg_trainer.py
(cherry picked from commit 68a96bb485cb0f411dce8c42d717da9e69362dee)
=> One last place where checkpoint_num_classes should be present (#1549)

Makefile
$@ is the name of the target being generated, and $^ are the dependencies
=> Fixed incorrect automatic variable used

src/super_gradients/training/utils/bbox_utils.py
Giving a second life to https://github.com/Deci-AI/super-gradients/pull/1556 PR which seems to be stale, but anyway worth merging
=> Reorder operators to ensure Neg operator is not used

requirements.txt
Fixes https://github.com/Deci-AI/super-gradients/issues/1626
=> Bump onnx-simplifier version require at least 0.4.3

src/super_gradients/training/utils/detection_utils.py
Thi PR fixes bug in ExtremeBatchDetectionVisualizationCallback (No targets are rendered)
=> Prevent modification of the input argument (targets) in DetectionVisualization.visualize_batch

README.md
- Update pre-trained models badge URL.
- Update some typos on README.
=> Update pre-trained models badge URL

README.md
Adding docs for voxel51 integration
=> Update README.md - voxel51 integration

src/super_gradients/common/environment/omegaconf_utils.py, tests/unit_tests/hydra_resolvers_test.py
Need mul and div to easily scale lr and other stuff based on batch, etc
=> Added more hydra resolvers

scripts/run_and_convert_notebook.sh
This is to have correct "pip install" in the notebook
=> Explicitly specify a kernel name that match the environment in CI

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/question.yaml
used the full image path and added a break line
=> added the Ask AI feature to bug report format.

src/super_gradients/training/utils/predict/prediction_pose_estimation_results.py
Minor changes made to `super_gradients.training.utils.predict.prediction_pose_estimation_results.
ImagePoseEstimationPrediction.save()`.
=> Solution to Issue #1972 - Corrected issue with pose estimation result image saving

src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
For discussion: do we want to apply BGR2RGB, channel swap, normalization, and other under-the-hood things when user asks to visualize *with transforms*?
=> Minor visualization fixes
