src/super_gradients/training/sg_model/sg_model.py

This change should allow POST_TRAINING phase callbacks to still use the sg_logger before it is closed

POST_TRAINING callbacks before closing sg_logger

---

src/super_gradients/common/sg_loggers/wandb_sg_logger.py

Version 1.4.0 has one extra parameter passed to `BaseSGLogger`'s `__init__`: `checkpoints_dir_path`.
It was added in: https://github.com/Deci-AI/super-gradients/commit/26497f3891d668b32ddfba066959c35c61bac0eb#diff-ebb69576351b4be27ebcfe050406dfb79ef52590cc77f213e829d7c30225ce30.
Since it is not apparent in `WandBSGLogger`, which initializes `BaseSGLogger` - an exception is thrown.

Fixed missing checkpoints_dir_path piping to base logger

---

src/super_gradients/common/decorators/factory_decorator.py
src/super_gradients/common/factories/transforms_factory.py
src/super_gradients/recipes/cityscapes_stdc_seg50.yaml
src/super_gradients/recipes/training_hyperparams/cityscapes_stdc_train_params.yaml
src/super_gradients/training/datasets/segmentation_datasets/segmentation_dataset.py
src/super_gradients/training/losses/all_losses.py
src/super_gradients/training/sg_model/sg_model.py
src/super_gradients/training/utils/segmentation_utils.py

- cleaned cityscapes_stdc_seg50 training from redundant _target_ calls as an example for the new factory
- fixed a bug in the factory decorator
- added stdc_loss to the losses list

- added a new factory for transforms

---

src/super_gradients/training/utils/segmentation_utils.py

fix augmentation when passing a list instead of a tuple (which happens when working with yamls)

fix pad short to crop size

---

src/super_gradients/training/models/segmentation_models/stdc.py

Fixed when replacing to static size context embedding, the weights are transferred to the new module.

fix stdc context conversion

---

src/super_gradients/recipes/arch_params/yolo_arch_params.yaml
src/super_gradients/recipes/arch_params/yolox_nano_arch_params.yaml
src/super_gradients/training/models/detection_models/csp_darknet53.py
src/super_gradients/training/models/detection_models/yolov5_base.py
src/super_gradients/training/models/detection_models/yolox.py

Adding new arch_param 'depthwise': False, which is needed for YOLOX-nano. When its True the following layers are replaced with depthwise-separable ones:
* `Conv`s* and blocks** in the backbone (all except `Focus`);
* Blocks and 2 last downsizing  `Conv`s in the head;
* `Conv`s in two branches in `DetectX` (all except Stem and predicting layers).
*Depthwise-separable Conv = `DepthWiseConv`
**Depthwise-separable block = a block with `DepthWiseConv` in Bottleneck
Changes in `C3` and `BottleneckCSP aren't backward-compatible, but these modules are used only in yolov5_base.py and csp_darknet53.py anyway.

fix: Build a correct YOLOX-nano with depthwise separable convs

---

src/super_gradients/training/losses/ssd_loss.py

The function `_norm_relative_box` does the inverse of what happens with the predicted values. 
The predicted values are **multiplied** by scale, so the targets should be **divided**. It is not a bug, just much more clear to read the formula like this. Confused me for some time, because I didn't notice the inverse of scale happening in init

refactor: Readable scale

---

src/super_gradients/training/losses/ssd_loss.py
src/super_gradients/training/utils/ssd_utils.py

Our SSD never predicts people because of the collapse between the background and person category. The fix can be achieved with either + 1 on targets or offset in the dataset. From these options I find +1 preferable, because I think it's purely about the loss. Especially since the post-prediction callback is meant to utilize the background class and get rid of it. So predicted classes will be 0-based, and so should be targets imo. 
One more reason: 0-based classes are consistent with [COCO_DETECTION_CLASSES_LIST](https://github.com/Deci-AI/super-gradients/blob/cf08b5dcb0a92b9e462731da447786aa7d22f2aa/src/super_gradients/training/datasets/datasets_conf.py#L1)
As for the part of the code removed in the callback, it is a patch for the bug explained above, so I'm removing it.
For clarity, the …

fix: Get people back their own class

---

src/super_gradients/recipes/arch_params/yolo_arch_params.yaml
src/super_gradients/training/models/detection_models/yolov5_base.py
tests/unit_tests/yolov5_unit_test.py

Fixing the usage of width multiplier for any YOLO-based model. We used to be able to construct only certain multiplier which aren't know in advance, but now any can be used, which is verified in the test I'm adding.
The problem was 2-fold:
1. Say someone attempts to use width_mult of 1.33. In this case the last head layer had input width_mult(1024), which is meant operate on two feature maps of width_mult(512) concatenated prior. But `int(1.33*512)` =  680, so the width after concat will be 680*2 = 1360, but `int(1.33*1024)` =  1361, which creates channel mismatch.
2. It's problematic to aways do `width_mult(connector[1])` where connector is a pre-calculated number of channels after concat between a head and a backbone layers. In such case using this head with a fixed backbone (no width …

fix: Support any model width multiplier

---

tests/unit_tests/yolov5_unit_test.py

This test is supposed to make sure that yolo's `initialize_param_groups(...)` method doesn't leave some parameters out. Can happen if you change an architecture, but forget about this function. But params that don't require grad, like anchors, etc, shouldn't be in optimizer's params. That's a fix

Fix failing yolo param groups test

---

src/super_gradients/training/models/classification_models/regnet.py

Minor but useful refactor. We often need this parsing outside of RegNetX class, so people just end up copy-pasting this code every time. Would like to be able to import it

refactor: Separate function for regnet slope to blocks

---

src/super_gradients/recipes/arch_params/yolo_arch_params.yaml
src/super_gradients/training/models/detection_models/csp_darknet53.py
src/super_gradients/training/models/detection_models/yolov5_base.py

* Custom intermediate channels and groups in DetectX branches;
* GroupedConvBlock instead of DWConv (support group sizes other than one)
I double-checked that these changes don't change state dicts of YOLOX-N and YOLOX-S (two models that use the affected `DetectX`, one with depthwise True and one with False)

feature: Add new options for anchorless detect module

---

src/super_gradients/training/metrics/detection_metrics.py

Synchronized metric state tensors are on different devices in DDP which causes the training to crash in compute().

state moved to metrics device

---

src/super_gradients/training/datasets/datasets_utils.py
src/super_gradients/training/models/detection_models/yolov5_base.py
src/super_gradients/training/utils/checkpoint_utils.py
tests/unit_tests/yolox_unit_test.py

- Old Focus block weights reshaped when reading ckpt to 6x6 conversation weights.
- Anchors are fixed to old COCO Anchors for compatibility and will be removed in the future.

Support for reading pretrained YoloX models with old blocks

---

src/super_gradients/training/datasets/datasets_utils.py
tests/deci_core_unit_test_suite_runner.py
tests/unit_tests/multi_scaling_test.py

DetectionMultiscalePrePredictionCallback was changed to keep in memory the state of the new rescale size.
Tests done:
- The unit test "MultiScaleTest" was added.
- The recipe "coco2017_yolox" was run without changing any parameter for 1 epoch (it uses DetectionMultiscalePrePredictionCallback)

Fix scale between rescaling batches

---

src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
tests/deci_core_unit_test_suite_runner.py
tests/unit_tests/detection_caching.py

Adding hash to the name of cached arrays, to make sure that next time we load the cache we will have the expected data.
To do so, the image size and image path are all combined to create the hash, that way if we have exactly the same image path and image size (regardless of the parameters) we will reload the cached array.

Hotfix detection cache: Add hash in name when caching

---

src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
src/super_gradients/recipes/coco2017_yolox.yaml
src/super_gradients/recipes/dataset_params/coco_detection_ssd_lite_mobilenet_v2_dataset_params.yaml
src/super_gradients/recipes/dataset_params/coco_detection_yolox_dataset_params.yaml

- Fix the experiment name to not include a whitespace
- Add default values to all parameters (class_inclusion_list, train_max_num_samples, ...)
- 
coco_detection_ssd_lite_mobilenet_v2_dataset_params and coco2017_yolox were tested

Fix coco recipes

---

src/super_gradients/training/utils/optimizer_utils.py

Fixed a crash in case a model's `initialize_param_groups` modifies `training_params`

fix: Prevent loosing weight_decay from params

---

src/super_gradients/recipes/checkpoint_params/default_checkpoint_params.yaml
src/super_gradients/recipes/imagenet_resnet50_kd.yaml
src/super_gradients/training/models/kd_modules/kd_module.py
src/super_gradients/training/utils/checkpoint_utils.py

Imagenet resent50 KD recipe was broken because of changes in https://github.com/Deci-AI/super-gradients/pull/319 .
(Input adaptor's parameters had require_grad=True which led to CUDA OOM).
Additionally map location=None in load_pretrained_weights caused to having extra GPU memory allocated in rank:0 when training in DDP. I removed it since the net is moved to the proper device in Trainer anyways.

teacher adpator freeze + map location cpu for all pretrained models

---

src/super_gradients/training/datasets/detection_datasets/detection_dataset.py

The images are loaded in detection dataset in BGR, so I think it's safe to assume whatever is plotted in the same class is always BGR and should be converted to RGB before displaying.
R.n. we are plotting creepy blue pics

fix: Plot detection in RGB

---

src/super_gradients/recipes/dataset_params/supervisely_persons_dataset_params.yaml
src/super_gradients/training/models/segmentation_models/ppliteseg.py
src/super_gradients/training/models/segmentation_models/stdc.py

Those changes are included:
* refactor supervisely dataset_params: right order of transformations, fix fill_mask from cityscapes
* Add replace_heads implementation for ppliteseg models

Fixes for segmentation notebooks

---

src/super_gradients/training/models/model_factory.py
src/super_gradients/training/utils/checkpoint_utils.py

Basically, we used to load the Trainer and now we load directly the module, but the code for load_backbone was not changed accordingly which broke the code when setting load_backbone=True

Fix load_backbone

---

src/super_gradients/common/environment/__init__.py
src/super_gradients/common/environment/environment_config.py

It seems that the env variable that is checked is never used, am I missing something ?
If it is never used, I don't see a reason to keep the check in the code, especially since it prints a message every time we import SG.

Remove AWS env check

---

src/super_gradients/training/utils/distributed_training_utils.py

PyTorch raises a warning when using torch.tensor instead of my_tensor.clone().detach().

Replace torch.tensor by my_tensor.clone().detach()

---

src/super_gradients/training/sg_trainer/sg_trainer.py
src/super_gradients/training/utils/distributed_training_utils.py

memory_cached is now deprecated by pytorch and we should use memory_reserved.
This will avoid a lot of warnings that we get in every run

FIX: Rename memory_cached

---

setup.py

Since README.md is in UTF-8 encoding, open() fails to read the file on non-mac platforms without explicit encoding argument.

Improve cross-platform compatibility when parsing a readme description

---

src/super_gradients/common/environment/env_helpers.py
tests/unit_tests/hydra_resolvers_test.py

Tiny pull request for hydra resolvers that I always create for myself and would be helpful to have on SG.
Example use-cases:
`add` - 
```
num_classes: 19
IoU:
num_classes: $num_classes + 1                 # not possible right now, very useful
num_classes: ${add: ${num_classes}, 1}
```
`cond` - 
```
partial_labels: True
full_num_classes: 19
partial_num classes: 8
n_classes: partial_num_classes if partial_labels else full_num_classes     # a if true else b
n_classes: ${cond: {$partial_labels}, ${partial_num_classes}, ${full_num_classes}}
```

added useful hydra resolvers with tests

---

src/super_gradients/training/models/segmentation_models/shelfnet.py
tests/unit_tests/shelfnet_unit_test.py

For some reason shelfnet was implementing with the naming classes_num instead of num_classes.
This breaks the logic defined in model_factory, which expects num_classes.

Rename shelfnet classes_num param

---

src/super_gradients/sanity_check/env_sanity_check.py

when env sanity check fails with an error, always print it to the screen and in red

when env sanity check fails - print error

---

src/super_gradients/common/environment/env_helpers.py
src/super_gradients/common/environment/environment_config.py
src/super_gradients/training/utils/checkpoint_utils.py
src/super_gradients/training/utils/distributed_training_utils.py

Currently, we don't pass the extra (non-hydra) args to the subprocesses. e.g. if you run `python my_script.py --config-name=config x=0 --y=1 ` then the subprocesses will get `python my_script.py --config-name=config x=0`. 
This is done so because hydra does not support extra args, so we drop it and currently we lose this information after @hydra.main
Solution: When "poping" the extra non-hydra args, we store them in a variable and which can later on be used when launching DDP subprocesses.
Depends on: https://github.com/Deci-AI/super-gradients/pull/464 (black formatting)

Fix: pass extra args to subprocesses in ddp

---

src/super_gradients/recipes/arch_params/unet_default_arch_params.yaml
src/super_gradients/training/models/segmentation_models/unet/unet.py

Dynamically setting the minimum num of channels w.r.t the num_classes can cause problems when applying transfer learning.
This parameters should be set explicitly.

explicit min_decoder_channels

---

src/super_gradients/common/environment/monitoring/monitoring.py
src/super_gradients/common/sg_loggers/base_sg_logger.py

This might lead to a situation where the TB is already closed and yet the system monitoring would try to write on TB

Prevent system monitoring to write after calling .close()

---

src/super_gradients/common/sg_loggers/base_sg_logger.py
src/super_gradients/training/sg_trainer/sg_trainer.py

- Support for (optional) additional configs to be logged in training's sg_logger.
- Full recipe config logged when launching train_from_config
- Small bug fix in base_sg_logger (all configs were added under the same tag=hyper_parameters).

SG-448- dataset_params and arch_params logging

---

src/super_gradients/training/models/segmentation_models/context_modules.py

prevent prep_for_conversion from crashing when called twice and global pooling modules were already converted to AveragePool modules.
fixed raising this error:
```
AttributeError: 'AvgPool2d' object has no attribute 'output_size' when I try to export to model.prep_model_for_conversion(input_size=input_size)
```

fix  pplite-seg prep conversion

---

src/super_gradients/training/sg_trainer/sg_trainer.py
src/super_gradients/training/utils/checkpoint_utils.py

Change introduced:
Now instead of evaluating training.ckpt_name, we first check if the checkpoint_path is provided. Only if it is not, we use training.ckpt_name.

Improve evaluate_from_recipe usability

---

src/super_gradients/common/factories/type_factory.py

PB:
hydra resolves "OFF" as a boolean, and we don't process booleans in the typefactory.

Fix Multigpu.OFF factory

---

src/super_gradients/common/abstractions/abstract_logger.py
src/super_gradients/common/auto_logging/__init__.py
src/super_gradients/common/crash_handler/exception_monitoring_setup.py
src/super_gradients/common/sg_loggers/base_sg_logger.py
tests/unit_tests/train_logging_test.py

Motivation:
- get_logger requires AutoLoggerConfig
- AutoLoggerConfig and ConsoleSink are imported together in the auto_logging package __init__
- ConsoleSink includes some DDP dependencies, which themselves require other imports
This often creates circular import loops that are hard to fix.
Solution:
Not importing ConsoleSink when importing AutoLoggerConfig

Import AutoLoggerConfig and ConsoleSink separatly

---

src/super_gradients/training/losses/dice_ce_edge_loss.py

Torch native cpp loss classes except only integer as ignore_index, the default is -100 for not using ignore.
While python based implementation use `None` as explicit indication for no using an ignore_index, see DiceLoss and torchmetrics.JaccardIndex class signatures.
This PR prevent passing an integer to `DiceLoss` that crash in the `to_one_hot` function due to an extra unnecessary ignore class, as follows:
```
File "/home/lior.kadoch/PycharmProjects/super-gradients/src/super_gradients/training/losses/dice_loss.py", line 28, in _calc_numerator_denominator
numerator = labels_one_hot * predict
RuntimeError: The size of tensor a (22) must match the size of tensor b (21) at non-singleton dimension 1
```

fix ignore index for DiceCEEdgeLoss

---

src/super_gradients/recipes/training_hyperparams/default_train_params.yaml

This "None" breaks the code because it is interpreted as a string.
to reproduce the error, you can run with --config-name=coco2017_yolox
Is it a bug? or did I miss something?
Just remove the default value, which automatically sets it to None

fix default value of max_train_batches, max_valid_batches

---

src/super_gradients/common/crash_handler/crash_tips.py

Small refacto class.
I want that any class inheriting from CrashTip is automatically registered, without needing to add the class to a list manually, because this step can easily be forgotten.

Register crashtips automatically

---

src/super_gradients/common/crash_handler/crash_tips.py
tests/unit_tests/crash_tips_test.py

Objectif: Give a hint when people don't write interpolation with full path starting from config file, which is required by hydra
Example: '${dataset_params.train_dataloader_params.batch_size}' (good) instead of '${train_dataloader_params.batch_size}' (bad).
Note: hydra doenst tell us in what config file this breaks so we cannot show the exact solution. Instead we give hints with a general example.

Interpollation crash tip

---

src/super_gradients/training/sg_trainer/sg_trainer.py

- Clipping was done each batch- moved to being done once before gradient step.
- Unscale gradients before preforming gradient step (note that unsealing is preformed in optimizer.step if not explicitly done, so only need to unscale them before clipping, more info https://pytorch.org/docs/stable/notes/amp_examples.html?highlight=gradient+clipping)

Fix grad clipping stage + upscale gradients before clipping

---

src/super_gradients/training/models/segmentation_models/unet/unet.py
src/super_gradients/training/models/segmentation_models/unet/unet_encoder.py

Allow setting any encoder output as auxiliary head with no constraints for the heads to be consecutive (as currently supported)
i.e this example is now supported:
```
aux_heads_factor: [ 2, 4, 8, 16, 32, 64 ]
use_aux_list: [False, False, True, False, True, False]
```

UNet aux heads customization

---

src/super_gradients/common/data_types/enum/strict_load.py
src/super_gradients/training/kd_trainer/kd_trainer.py
src/super_gradients/training/utils/checkpoint_utils.py
tests/deci_core_unit_test_suite_runner.py
tests/unit_tests/load_checkpoint_test.py

This PR adds `StrictLoad.KEY_MATCHING` mode to do partial checkpoint load. This is different from `.load_state_dict(state_dict, strict=False)` in one but critical part - if the layer has matching name, but shape is different, we will just skip this layer and load what has matching shape, ignoring the rest. Vanilla `load_state_dict` would just raise an error.
See https://github.com/Deci-AI/super-gradients/blob/09c0c0d6ca966a84fc320566fa410fc233770bae/tests/unit_tests/load_checkpoint_test.py#L10 test to get the idea what it does.
The motivation for this change is to have an ability to do partial checkpoint load. In case of DEKR, the pretrained weights comping from another repo and NO_KEY_MATCHING load strategy cannot do the work. `NO_KEY_MATCHING` doing index-based loading and it puts very …

Introduce transfer_weights and StrictLoad.KEY_MATCHING mode

---

src/super_gradients/training/utils/checkpoint_utils.py

Somehow failing unit test did not marked build as red, so it slipped into master in #733 PR. 
This hotfix address the issue that strict sometimes can be just an ordinary bool

Fix the case when strict value could be just a boolean variable.

---

src/super_gradients/recipes/dataset_params/coco_detection_dataset_params.yaml
src/super_gradients/recipes/dataset_params/coco_detection_ssd_lite_mobilenet_v2_dataset_params.yaml
src/super_gradients/recipes/dataset_params/pascal_voc_detection_dataset_params.yaml
src/super_gradients/training/datasets/samplers/infinite_sampler.py

This PR removes `InfiniteSampler` from default COCO dataset config. 
The motivation for this change is this class causes random crashes in DataLoader with num_workers > 0. 
It was not traced till the very end, but presumably due to the way this class is implemented (Sampler has no "ending"). 
For instance, following snippet cause crash on Windows:
```
if __name__ == "__main__":
dataset = list(range(1123123))
sampler = InfiniteSampler(dataset, shuffle=True, seed=0, rank=0, world_size=1)
for batch in tqdm(DataLoader(dataset, batch_size=32, drop_last=False, sampler=sampler, num_workers=4), desc="InfiniteSampler"):
pass
print("Iterationg over dataset done")
```
It also ensures that `drop_last: True` is set to avoid rare but possible case when last batch would have size 1 and this would crash …

Remove InfiniteSampler from base configs for COCO

---

src/super_gradients/training/losses/ppyolo_loss.py

Fixes an extremely rare case when batch has zero target bboxes.

Fix incorrect tensor type & device when entire batch has no targets

---

src/super_gradients/training/datasets/detection_datasets/__init__.py
src/super_gradients/training/datasets/detection_datasets/coco_detection.py
src/super_gradients/training/datasets/detection_datasets/coco_format_detection.py
src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
src/super_gradients/training/datasets/detection_datasets/roboflow/roboflow100.py
src/super_gradients/training/datasets/detection_datasets/yolo_format_detection.py
src/super_gradients/training/utils/load_image.py

This does the job, but:
Do we want to add recipe ? If we don't, we cannot register dataloader (which when we think about it is a little annoying)
What seems like a bad design. A cleaner design would be to have the format as an input parameter. 
With the design I just pushed, if we want to add explicit support to robolow and coco we would need to implement 1 new class for each that would inherit from `Yolov5Formated...`. 
Having the format as a parameter would 1. reduce the amount of code and 2. be nicer and easier to use. The downside is that it would require some more work for this one PR and we might not want that.

Add support to yolov5 format dataset

---

src/super_gradients/examples/predict/detection_predict_video.py
src/super_gradients/training/pipelines/pipelines.py

Currently, Pipeline expects an optional device as params, which by default is 'cpu'. But, this param is not set when we instantiate the pipeline inside `model.predict(...)`
This means that the model always runs on cpu inside `model.predict(...)`.
I propose to just run on the same device as the model, unless the pipeline was explicitely instantiated with a device.

Use model device in predict

---

src/super_gradients/common/auto_logging/auto_logger.py

This is relevant for tests, that run multiple test cases in the single process.
This PR ensures that we close all file handles before setting up new logger

Fix leaking file-handle in logger

---

src/super_gradients/modules/qarepvgg_block.py
src/super_gradients/modules/repvgg_block.py

On the left is unfused, on the right - fused

Add missing calls to RepVGG blocks to fuse layers

---

src/super_gradients/training/datasets/data_formats/bbox_formats/cxcywh.py

Fix for `.../home/circleci/project/venv/lib/python3.7/site-packages/super_gradients/training/datasets/data_formats/bbox_formats/cxcywh.py:103: UserWarning: Detected non floating-point input (torch.float32) to xyxy_to_cxcywh_inplace function. This may cause rounding errors and lose of precision. You may want to convert your array to floating-point precision first.
`

Fixed false-positive warning message 

---

src/super_gradients/training/datasets/datasets_utils.py
src/super_gradients/training/utils/callbacks/callbacks.py

This small PR fixes wrong import of `deprecate` package that we do not declare in our requirements.
Instead we use `deprecated`. So I changed that. The motivation for this fix is when we loose some of our requirements, the `deprecated` package is not installed anymore and we get import error because of that.

Update deprecate -> deprecated

---

.circleci/config.yml
requirements.txt
src/super_gradients/recipes/coco2017_pose_dekr_w32_no_dc.yaml
tests/unit_tests/detection_utils_test.py
tests/unit_tests/lr_cooldown_test.py
tests/unit_tests/lr_warmup_test.py

- Fixed some failing tests in build after moving it to run on 3.8.
- Moved build to run on 3.8 (minimum python version requirement for torch 2.0)
- Fixed missing arch_params.num classes that were missing for pose estimation regression test.
- Updated requirement, pip version in CI.

Feature/sg 850 support torch 2.0

---

src/super_gradients/training/sg_trainer/sg_trainer.py

I am not sure why this error happens to begin (see https://github.com/Deci-AI/super-gradients/issues/967), and I couldnt reproduce it, but this should fix it:
- Make the code more robust to this type of error
- Raise a more explicit error when user doesnt provide a loader and not loader found in cache.

Fix train_loader not initalized properly

---

src/super_gradients/training/utils/weight_averaging_utils.py

- In line 52 we save the state dict even if it was just read. Saving is just for the first time we create the state_dict of the snapshots, so the saving is moved inside the else statement when we check if we resume or not.

Fixed resuming training with DDP when average_best_models=true

---

src/super_gradients/training/models/model_factory.py
src/super_gradients/training/utils/checkpoint_utils.py
tests/unit_tests/load_checkpoint_test.py

- Allow checkpoint_path to be an url (Required for transfer learning)
- Added synchronization primitives to prevent race conditions when downloading weights
One can now load checkpoints like so:
```
models.get(Models.YOLO_NAS_S, num_classes=80, checkpoint_path="https://sghub.deci.ai/models/yolo_nas_s_coco.pth")
```
Why we want this to have: For training YOLO-NAS-POSE we want to use YOLO-NAS-OD pretrained weights like so:
```
checkpoint_params:
checkpoint_path: "https://sghub.deci.ai/models/yolo_nas_s_coco.pth"
```
This PR enables us to do this.

Allow checkpoint_path to be an url (Required for transfer learning)

---

src/super_gradients/training/utils/checkpoint_utils.py

Fix incorrect use of collections.OrderedDict in type annotation

---

src/super_gradients/training/utils/utils.py

In Colab notebooks Python 3.10 is already a thing. And importing collections.Iterable does not work anymore. This fixes broken import

Fix collections.Iterable -> typing.Iterable to fix crash in python 3.10

---

src/super_gradients/training/transforms/utils.py

This leads to hard-to-debug bugs in transforms, when image first normalized, then resized and then float image casted to byte.

Remove casting to uint8 during resize

---

documentation/source/Checkpoints.md

Hello there👋
I have made a pull request to fix a small typo in the documentation.

Fixed typo 'perfroming' -> 'performing'

---

src/super_gradients/training/metrics/detection_metrics.py
src/super_gradients/training/utils/detection_utils.py

This PR allows to pass user-defined target of IoU thresholds without asking user to edit IoUThresholds enum in SG codebase:
```
valid_metrics_list:
- DetectionMetrics:
iou_thres: [0.5, 0.8]
```
Note that this does not solve the problem of having two instances of `DetectionMetrics` in `valid_metrics_list`, but it allow to pass iou_thres as a tuple which we do not allow at the moment

Allow passing tuple of [low, high] to iou_thresholds parameter in DetectionMetrics.

---

src/super_gradients/training/models/model_factory.py
src/super_gradients/training/utils/checkpoint_utils.py

The request came from @eran-deci and aims at letting the user know when we are properly loading pretrained weights and whether or not it was downloaded from the platfrom.

Addiing more logs to let user know when pretrained_weights is being used, and/or downloaded

---

mkdocs.yml

Adding the tutorial to the website that includes all the documentation

Add model export tutorial to documentation website

---

src/super_gradients/training/models/detection_models/yolo_base.py

Explicitly remove the stride keys from the checkpoint if they are present which should fix the issue with DeciDet checkpoints
Since these models are also utilizing Anchors class previously, those must be deleted explicitly

Bugfix: Fix loading DeciDet models that has anchors keys in state dict.

---

src/super_gradients/module_interfaces/module_interfaces.py
src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
src/super_gradients/training/datasets/pose_estimation_datasets/base_keypoints.py
src/super_gradients/training/datasets/pose_estimation_datasets/coco_keypoints.py
tests/unit_tests/preprocessing_unit_test.py

* BaseKeypointsDataset now inherits from HasPreprocessingParams to ensure preprocessing params for pose estimation model are saved properly.
* Changed default confidence threshold from 0.25 to 0.05 to match the default confidence threshold as is training recipe.
SupportsReplaceNumClasses and HasPreprocessingParams are no Protocols anymore.
Motivation:
A Protocol class seems to do a lot of black vodoo magic:
```python
class HasPreprocessingParams(Protocol):
...
class DetectionDataset(Dataset): # No HasPreprocessingParams
...
class COCODetectionDataset(DetectionDataset)
dataset = COCODetectionDataset(...)
isinstance(dataset, HasPreprocessingParams) # Returns True :exploding_head: 
```
Even not inheriting from HasPreprocessingParams but having the methods with matching signature implement, …

BaseKeypointsDataset now inherits from HasPreprocessingParams

---

src/super_gradients/module_interfaces/__init__.py
src/super_gradients/training/models/detection_models/yolo_nas/dfl_heads.py

Hotfix to support 1 or 2 heads in YoloNAS and minor fix to imports

Hotfix/sg 000 Fix support of arbitrary number of heads

---

src/super_gradients/common/factories/base_factory.py
src/super_gradients/common/factories/type_factory.py
src/super_gradients/common/registry/registry.py
tests/unit_tests/test_registry.py

Use the class names instead of custom snake_case format to name objects
This PR introduces the logic to deprecate old snake_case names.
Check the unittest to better understand the logic.
Changing the registration names will be done in followup PRs for more clarity (you check out this PR https://github.com/Deci-AI/super-gradients/pull/1446 which will introduce the first object renaming)

Adding a deprecation option into registeries

---

tests/breaking_change_tests/code_parser.py
tests/breaking_change_tests/unit_test.py

Let's imagine we change the code
FROM
```python
class MyClass:
def method(self): pass
```
TO
```python
class MyNewClass:
def method(self): pass
class MyClass(MyNewClass): pass
```
This is **NOT** a breaking change, because `MyClass` inherits from `MyNewClass` which still includes `method`.
**Issue**: current class signature extractor (implemented as part of the breaking change detection) currently misses this and will raise that the new `MyClass` does not include `method`.

Fix Breaking Change Detection on Inheritence

---

src/super_gradients/training/utils/callbacks/callbacks.py
src/super_gradients/training/utils/utils.py
tests/unit_tests/extreme_batch_cb_test.py

* Allow user to control whether to run on train and/or validation loaders
* Allow to control maximum number of logged images
* Store extreme batch on CPU
* OD visualization of batches changed to render side-by-side (pred-gt) images per image (This is mainly to allow easy understanding in W&B since old implementation was showing whole plot of GT batch first, then you had to scroll down to see Pred batch and go up and down to compare prediction for certain sample => not convinient)

Improve extreme batch visualization callbacks

---

src/super_gradients/training/dataloaders/dataloaders.py

Otherwise string collate FN would not be instantiated properly IF dataloader name is None and dataset name is present in dataloader params

A call to _process_collate_fn_params was missing in dataloaders.get.

---

src/super_gradients/training/utils/distributed_training_utils.py
src/super_gradients/training/utils/utils.py

Minor PR with two changes:
* Inside `maybe_all_reduce_tensor_average` we enforce reduced tensor is dense. Got crash when tried to observe a specific loss component (`loss[4]` and since indexing does not create a new tensor but rather a view this failed to work with all_reduce).
* `convert_to_tensor` now create tensor from numpy in a bit more efficient fashion straight on target device.

Small improvements to utils

---

src/super_gradients/training/sg_trainer/sg_trainer.py
src/super_gradients/training/utils/callbacks/base_callbacks.py
src/super_gradients/training/utils/callbacks/callbacks.py

ExtremeBatchCaseVisualizationCallback will also store additional_batch_items for extreme batch.
For pose estimation we cannot rely on `targets` to visualize groundtruth (DEKR & YoloNAS has completely different targets format). In contrast we can easily get groundtruth data directly from `additional_batch_items`. 
Since we also don't want to rely on specific keys from this dictionary, I thought it make sense to store `additional_batch_items` as is in the `context`. This way we can refer to the `additional_batch_items` as a whole and also not break existing metrics that rely on upacking this dict into context.

ExtremeBatchCaseVisualizationCallback now has access to additional_batch_items

---

src/super_gradients/training/processing/processing.py

When creating Processing instances some arguments may be not Tuple but ListConfig (Coming from transforms) and then they silently serialized to state dict with pickle. By adding explicit casting to primitive tuple type we fix that.
The problem with ListConfig in state dict is when unpickled, it forces import of super_gradients.
E.g `torch.load(yolo nas checkpoint)` line would import SG, create logger and all that unexpected stuff.

Fix serialization of ListConfig in checkpoint state dictionary

---

src/super_gradients/recipes/checkpoint_params/default_checkpoint_params.yaml
src/super_gradients/training/kd_trainer/kd_trainer.py
src/super_gradients/training/sg_trainer/sg_trainer.py

Fixes a bug that `checkpoint_num_classes` cannot be set through YAML file:
Use case: Downloaded pre-trained checkpoint from sghub locally and want to train a model with 1 class instead of 80. Since it's local checkpoint, not using `pretrain_weights` but `checkpoint_path`. In this case must specify `checkpoint_num_classes` but it is not propagated properly.
```
checkpoint_params:
checkpoint_num_classes: 80
num_classes: 1
checkpoint_path: /yolo_nas_m_coco.pth
strict_load: key_matching
```

Ensure that `checkpoint_num_classes` is propagated from YAML to model

---

src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
src/super_gradients/training/datasets/detection_datasets/yolo_format_detection.py
tests/deci_core_unit_test_suite_runner.py
tests/unit_tests/detection_dataset_test.py

Cherry-picking https://github.com/Deci-AI/super-gradients/pull/1536 to master_330
---
* first draft
* fix
* fix
* fix detectiondataset
* Ensure that `checkpoint_num_classes` is propagated from YAML to model (#1533)
* Ensure that `checkpoint_num_classes` is propagated from YAML to models.get()
* Red checkpoint_num_classes via get_params
* Fixed a bug in export() that prevented to export model for BS>1 (#1530)
* Remove unnecessary files (#1540)
* remove check on base class
---------

Check class_id validity in DetectionDataset (#1536)

---

src/super_gradients/training/sg_trainer/sg_trainer.py
src/super_gradients/training/utils/sg_trainer_utils.py

As @BloodAxe described, if _training_hyperparams.max_train/valid_batches_ are redefined in CLI, _tqdm_ and training log do not take changes into account and continue showing the full length of the dataloader. E.g. when user executes something like this
```
train_params = {
"max_epochs": 300,
"phase_callbacks": phase_callbacks,
"initial_lr": lr,
"loss": loss_fn,
"optimizer": optimizer,
"train_metrics_list": [Accuracy(), Top5()],
"valid_metrics_list": [Accuracy(), Top5()],
"metric_to_watch": "Accuracy",
"greater_metric_to_watch_is_better": True,
"lr_scheduler_step_type": "epoch",
"max_train_batches": 24,
"max_valid_batches": 24,
}
trainer.train(model=net, training_params=train_params, train_loader=train_loader, valid_loader=valid_loader)
```
the resulting logs and progress bar are the …

[Improvement] max_batches support to training log and tqdm progress bar.

---

src/super_gradients/conversion/conversion_utils.py

Exception when using SG with `numpy==1.25.2`
```
(torch.bool, np.bool),
../../../../miniconda3/envs/louis-dev/lib/python3.8/site-packages/numpy/__init__.py:305: in __getattr__
raise AttributeError(__former_attrs__[attr])
E   AttributeError: module 'numpy' has no attribute 'bool'.
E   `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
E   The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
E       https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
`(torch.bool, np.bool),` -> `(torch.bool, bool),`

Remove `np.bool` which is not supported in latest np versions

---

requirements.txt

For some reason cherry-pick of the corresponding commit from master failing. So manually bumping version here. Otherwise github showing merge conflict master -> master_330

Update Data Gradients version in master_330 branch

---

src/super_gradients/training/models/detection_models/yolo_base.py

On torch 1.12 arange_cpu is not implemented for fp16
Fix is to create arange with fp32 and then cast to fp16.

Fixed issue with torch 1.12 issue with arange not supporting fp16 for CPU device.

---

src/super_gradients/__init__.py
src/super_gradients/training/utils/callbacks/extreme_batch_pose_visualization_callback.py

Fixed bug in handling keypoint_colors/edge_colors/edge_links argumens in ExtremeBatchPoseEstimationVisualizationCallback that prevented instantiation of this class when params above were not instances of ListConfig type.
Side note: PR into master_330, let's try releasing from this branch

Bugfix: Cannot ExtremeBatchPoseEstimationVisualizationCallback when keypoint_colors is not ListConfig

---

src/super_gradients/training/sg_trainer/sg_trainer.py
tests/end_to_end_tests/trainer_test.py

@BloodAxe said SG does not support saving metrics, environment, and train config to the checkpoint.
After getting more familiar with a codebase, I realized the task should be split into several parts / PRs. This is a second one ;)
This PR proposes a way to add an environment/libs version to a separate field in the checkpoint .pth file.

Added packages to pth checkpoint

---

src/super_gradients/training/utils/weight_averaging_utils.py
tests/deci_core_unit_test_suite_runner.py
tests/unit_tests/test_model_weight_averaging.py

A class was not checking whether observed metric is a finite number and included a state dict of the model that had inf/nan metric value into averaging. 
The fix was three-liner:
```
val = float(validation_results_dict[self.metric_to_watch])
if not np.isfinite(val):
return False, None
```

Fixed bug in ModelWeightAveraging class that led to corrupted model when metric to watch was NaN/Inf

---

tests/unit_tests/test_convert_recipe_to_code.py

Removing `feature_version` because it's not supported in `python==3.7`

remove ast feature_version

---

notebooks/how_to_use_knowledge_distillation_for_classification.ipynb
notebooks/transfer_learning_classification.ipynb
notebooks/what_are_recipes_and_how_to_use.ipynb
notebooks/yolo_nas_pose_eval_with_pycocotools.ipynb
requirements.txt
src/super_gradients/__init__.py
src/super_gradients/scripts/export_recipe.py

__version__ bump to 3.4.1
data-gradients requirement updated to >= 0.3.0
fixed export_recipe.py config-dir default value

Fixes for 3.4.1 release

---

documentation/source/Data.md
src/super_gradients/common/environment/cfg_utils.py
src/super_gradients/training/sg_trainer/sg_trainer.py
tests/unit_tests/configs/cifar10_multiple_test.yaml
tests/unit_tests/train_with_intialized_param_args_test.py

How it supposed to look in YAML file
```
defaults:
- cifar10_resnet
test_dataloaders:
cifar10: cifar10_val
cifar100: cifar100_val
dataset_params:
test_dataset_params:
cifar10:
root: ./data/cifar10
train: False
transforms:
- Resize:
size: 32
- ToTensor
- Normalize:
mean:
- 0.4914
- 0.4822
- 0.4465
std:
- 0.2023
- 0.1994
- 0.2010
target_transform: null
download: True
cifar100:
root: ./data/cifar100
train: False
transforms:
- Resize:
size: 32
- ToTensor
- Normalize:
mean:
- 0.4914
- 0.4822
- 0.4465
std:
- 0.2023
- 0.1994
- 0.2010
target_transform: null
download: True
hydra:
searchpath:
- pkg://super_gradients.recipes
```

Added support of multiple test loaders in train_from_config

---

src/super_gradients/convert_recipe_to_code.py

I added **double quotes** around the name parameter in dataloaders.get() in the code below.
```
train_dataloader = dataloaders.get(
name="{train_dataloader}",
dataset_params={train_dataset_params},
dataloader_params={train_dataloader_params},
)
val_dataloader = dataloaders.get(
name="{val_dataloader}",
dataset_params={val_dataset_params},
dataloader_params={val_dataloader_params},
)
```

Fix Invalid syntax at convert_recipe_to_code.py

---

src/super_gradients/common/factories/transforms_factory.py
src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
src/super_gradients/training/samples/detection_sample.py
src/super_gradients/training/transforms/pipeline_adaptors.py
src/super_gradients/training/utils/detection_utils.py
tests/integration_tests/albumentations_test.py

- Introduces albumentations support, as done in the added integration test.
- Fixed DetectionDataset.plot() to support channels last.
- Fix for np.array.clip instead of torch.clamp in sanitise_sample.
- Call sanitize_sample after each transform and on init to ensure nothing has been corrupted.

Albumentations support for detectionsample

---

src/super_gradients/training/losses/ohem_ce_loss.py

OhemLoss forward, if all pixels are ignore labels, return empty loss tensor and pass it to logits device

 OhemLoss: bug fix

---

src/super_gradients/training/transforms/transforms.py

When YoloXTrainingStageSwitchCallback triggers a disable of DetectionMixup there is a bug that prevents No-Op flow of this transform

Fixed bug in DetectionMixup implementation that prevents YoloXTrainingStageSwitchCallback to work as intended

---

src/super_gradients/recipes/training_hyperparams/coco2017_ppyoloe_train_params.yaml
src/super_gradients/recipes/training_hyperparams/coco2017_yolo_nas_train_params.yaml
src/super_gradients/training/losses/ppyolo_loss.py

This PR drops the necessity to specify `reg_max` argument in the Loss which should match with the reg_max in the model.
We have all the infromation to infer it's value solely from model's outputs.

PPYoloELoss not does not require reg_max parameter

---

src/super_gradients/modules/qarepvgg_block.py
src/super_gradients/modules/repvgg_block.py

A RepVGG block has default alpha value of 1. This parameter controls the scalar multiply factor for residual branch. During NAS benchmarking of the model usually done using randomly initialized weights.
In this case a default value of 1 is simplified by ONNX so operation `alpha * x` reduced to simple addition. Elimination of multiplication makes the benchmark result a bit too optimistic. 
After model has been trained this alpha most likely will have the value that is different from 1 and hence the graph will contain the multiplication.
Adds a small noise to default value such that multiplication is not eliminated from the graph for model with random weights.

Fix potential unwanted simplification of ONNX graph when exported model with random weights

---

src/super_gradients/training/utils/callbacks/callbacks.py
tests/unit_tests/lr_warmup_test.py

This fix makes sure that either `lr_updates` contains something (non-empty list), or `step_lr_update_freq` exists, but not both.
In case where `lr_updates` is not set then it defaults to an empty list, which has no impact on the scheduler - but the code works -- not the best UX

changes logic from only one to exactly one parameter for step lr

---

tests/unit_tests/export_onnx_test.py

In https://github.com/pytorch/vision/releases/tag/v0.17.0 release a default value of antialias argument was changed. New value is incompatible with ONNX models.
So this PR adds explicit old value to keep tests green

Added explicit antialias=False to ensure we can export torchvision Resize to ONNX

---

src/super_gradients/training/datasets/detection_datasets/coco_format_detection.py

Why: in cases where the data is stored in a read-only directory, we would like to be flexible with different annotation files (e.g., pseudo-labels) - not having to put them under the `data_dir` (which we might not have access to).

allow flexibility to provide absolute path to annotations

---

src/super_gradients/training/utils/callbacks/callbacks.py

returned FunctionLRScheduler (looks like it was dropped by mistake)

YoloNAS_Pose_Fine_Tuning_Animals_Pose_Dataset

---

requirements.txt

* Conflict when installing dvc. It requires a more recent version
* Package is no longer used in the project and originates from old version
Like said in [this old PR](https://github.com/Deci-AI/super-gradients/pull/1923) with @BloodAxe , I removed the pyparsing from requirements and updated the commit following the contribution guidelines

Removed unsused pyparsing

---

requirements.txt

After merging https://github.com/Deci-AI/super-gradients/pull/1946 an issue popped up with missing `imagesize` dependency in Yolo format dataset.
Probably it came as a bonus from `sphinx`. Since `sphinx` is not with us anymore `imagesize` was not installed and caused test to fail. Added latest `imagesize` dependency

Added imagesize dependency

---

src/super_gradients/training/models/detection_models/pp_yolo_e/pp_yolo_head.py
src/super_gradients/training/models/detection_models/yolo_nas/dfl_heads.py
src/super_gradients/training/models/pose_estimation_models/yolo_nas_pose/yolo_nas_pose_ndfl_heads.py

It seems existing call to `F.conv2d` to compute weighted sum of box size distributions predictions confuses OpenVINO quantizers. This PR replaces this operation with simple multiplication which is equivalent op and works well for both TRT & Vino.

OpenVINO-friendly heads  for YoloNAS & YoloNAS-Pose

---

src/super_gradients/training/sg_trainer/sg_trainer.py

This PR fixes an issue in logging of train config object.
For logging we want non-instantiated config to be logged, so the fix is to resolve config first and retain this copy for logging and then instantiate it.
Reference: https://github.com/Deci-AI/super-gradients/issues/1986

Fixed issue of logging hydra-instantiated config

---

documentation/source/Dataset_Setup_Instructions.md
mkdocs.yml
src/super_gradients/examples/dota_prepare_dataset/dota_prepare_dataset.py
src/super_gradients/module_interfaces/__init__.py
src/super_gradients/module_interfaces/obb_predictions.py
src/super_gradients/recipes/dataset_params/dota2_yolo_nas_r_dataset_params.yaml
src/super_gradients/training/datasets/__init__.py
src/super_gradients/training/datasets/datasets_conf.py
src/super_gradients/training/datasets/obb/__init__.py
src/super_gradients/training/datasets/obb/abstract_obb_dataset.py
src/super_gradients/training/datasets/obb/collate.py
src/super_gradients/training/datasets/obb/dota.py
src/super_gradients/training/metrics/__init__.py
src/super_gradients/training/metrics/detection_metrics.py
src/super_gradients/training/metrics/obb_detection_metrics.py
src/super_gradients/training/pretrained_models.py
src/super_gradients/training/processing/__init__.py
src/super_gradients/training/processing/defaults.py
src/super_gradients/training/processing/obb.py
src/super_gradients/training/utils/callbacks/__init__.py
src/super_gradients/training/utils/callbacks/extreme_batch_obb_visualization_callback.py
src/super_gradients/training/utils/predict/__init__.py
src/super_gradients/training/utils/predict/prediction_obb_detection_results.py

This PR adds 
- DOTA2 dataset implementation 
- Script to prepare dataset files.
- Metric implementation (mAP for rotated boxes)

Added DOTA2 dataset

---

src/super_gradients/training/transforms/transforms.py

This fixed the `target-size` for DetectionRandomAffine as explained in #2011. It already takes into account if a specific `target-size` is set or the image shape is used.

Fix DetectionRandomAffine target-size to be in row-column format
